#!/bin/bash

# Cloning Repo with Dotfiles and go to Directory
git clone https://github.com/swchck/dotfiles.git ~/dotfiles && cd "$_" || echo 'Directory not Found!'

# Install Brewery
if [ -z "$(which brew)" ]; then
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

# Install Python
if [ -z "$(which python3)" ]; then
  brew update
  brew install python@3.10
fi

# Install RCM
if [ -z "$(which rcm)" ]; then
  brew install rcm
  env RCRC=~/dotfiles/rcrc rcup
fi

# Updating PIP
pip3 install --upgrade pip

# Install Python Dependencies
pip3 install -r -q installation/requirements.txt

# Installation Script
python3 installation/bootstrap.py