#!/bin/bash

#######################
# Pre Install Script
#######################

# Install Brewery
if [ -z "$(which brew)" ]; then
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

# Install Git on Linux Host or Developer tools on MacOS
if [[ "$OSTYPE" == "darwin"* ]]; then
  xcode-select --install
elif [[ "$OSTYPE" == "linux-gnu"* || "$OSTYPE" == "freebsd"* ]]; then
  if [ -z "$(which git)" ]; then
    brew install git
  fi
fi

# Cloning Installer and go to Directory
CONFIGURATIONS_DIR=$(mktemp -d)
INSTALLER_DIR=$(mktemp -d)
git clone https://github.com/swchck/dotfiles.git "$INSTALLER_DIR" && cd "$_" || echo 'Directory not Found!'
git clone -b default_configurations https://github.com/swchck/dotfiles.git "$CONFIGURATIONS_DIR" &&
 cd "$_" || echo 'Directory not Found!'

# Install Python and Dependencies
if [ -z "$(which python3)" ]; then
  brew update
  brew install python@3.10
  pip3 install --upgrade pip
  pip3 install -q pyinquirer PyGithub
fi

# Install RCM
if [ -z "$(which rcm)" ]; then
  brew install rcm
  env RCRC=~/dotfiles/rcrc rcup
fi

#######################
# Installation Script
#######################

python3 bin/bootstrap

#######################
# Post Install CleanUp
#######################

# Delete Installer Directory
rm -rf "$INSTALLER_DIR" "$CONFIGURATIONS_DIR"